### ISSUE TITLE
pointer-tracker not found

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChromeLabs/pinch-zoom#4]
When including this module in a typescript project, it reports that 'pointer-tracker' is not found (also noted when I do a roll-up build) it looks like it has been locally resolved.

The dist/ folder output has a reference to it, but the source doesn't - src/index.ts mentions it in an import, but it's not resolved. It looks like https://github.com/GoogleChromeLabs/pointer-tracker exists so I think it needs to be a dep in the package.json

**Comment by PaulKinlan** [comment]
Wait - it is in the package.json - I am not sure what issue I am having.  Will update or close this thread.

**Comment by IagoSRL** [comment]
I had this issue too, in my case because Webpack resolved to the file declared in the `module` property of the package.json (that is 'dist/pinch-zoom.mjs').

The pointer-tracker module is referenced at `devDependencies`, so is not installed when just importing pinch-zoom in a project. I think should be declared at `dependencies` so is automatic, or almost at `peerDependencies` so the need for the additional install is noticed.

Curiously, when another dist file is used (like the one pointed at the `main` property), this comes bundled so is not an issue. Unsure of the best practice on this cases.

**Comment by nolanlawson** [comment]
I'm working around this at the moment using

```js
import 'pinch-zoom-element/dist/pinch-zoom.js')
```

I think the fix is in either bundling pointer-tracker with the `dist` output and making it a true dev dependency, or leaving the import/require intact when bundling to `dist`. Either one works.
